Add ecbooster.md
feedforce/about-us pull request #3
Opened 2021-04-13 10:45 UTC by sukechannnn

## Overview

EC Booster の技術スタックを新規で追加しました。
元の esa 記事は[こちら](https://feedforce.esa.io/posts/86538)。

## Todo

- [ ] [文中に埋め込んでるスライド](https://docs.google.com/presentation/d/1gWraBK3XKDNdzI9aCXqEJ4Kahg19XIDz0v6pCun3EKs/edit?usp=sharing) の外部への公開期限を無期限にする依頼をする to @meihong

2021-04-13 10:48 UTC, sukechannnn commented
[GFM](https://github.github.com/gfm/) は iframe 埋め込めなかった...。
変わりに画像を埋め込みます。

2021-04-14 03:26 UTC, sukechannnn commented
![スクリーンショット 2021-04-14 12 25 13](https://user-images.githubusercontent.com/12433221/114650068-8b800480-9d1c-11eb-8245-18e99721003b.png)

👆の画像と一緒にスライドへのリンクを貼る。

2021-04-14 04:31 UTC, meihong requested changes
概ね大丈夫だとは思いますが、

- リンク先スライドで、権限不足で外部から開けないスプレッドシートへのリンクがあること
- 62行目「詳細はこちら的な何か」

は修正した方がいいかと思います。

2021-04-14 04:31 UTC, meihong commented on teams/ecbooster.md
> +- [EC Booster 開発スプリント回し方](https://docs.google.com/presentation/d/e/2PACX-1vTQY639rUAwDDtLfj_c9WbU1E0IlDSFzAbrP-XFCmbg8V_sNKPX_pCvKpiy50CQpS02nXvZnQHBb6JT/pub?start=false&loop=false&delayms=3000)
今更なのですが、外部向けに修正したほうが良さそうと思ったのが何点か。

- p5「ペアデザ」; 認識の齟齬を生まないために省略しない方がよいかも?
- p8「開発スケジュールのスプレッドシート」; 外部からはスプレッドシートが閲覧できないので、リンクは外した方がいいかも?

「ペアデザ」はそれ単体でも分かる気もしますが、スライド内リンクだけは外した方がよいかと思います。

2021-04-14 04:31 UTC, meihong commented on teams/ecbooster.md
> +    - 詳細はこちら的な何か
ここは修正が必要では?
[スライド4ページ目へのリンク](https://docs.google.com/presentation/d/e/2PACX-1vTQY639rUAwDDtLfj_c9WbU1E0IlDSFzAbrP-XFCmbg8V_sNKPX_pCvKpiy50CQpS02nXvZnQHBb6JT/pub?start=false&loop=false&delayms=3000&slide=id.gcefcb55f74_0_16)を貼っておけばよいかと思います。

2021-04-14 04:45 UTC, sukechannnn commented on teams/ecbooster.md
> +- [EC Booster 開発スプリント回し方](https://docs.google.com/presentation/d/e/2PACX-1vTQY639rUAwDDtLfj_c9WbU1E0IlDSFzAbrP-XFCmbg8V_sNKPX_pCvKpiy50CQpS02nXvZnQHBb6JT/pub?start=false&loop=false&delayms=3000)
ありがとうございます！スライド修正しました 🙆 

- ペアデザ ⇢ デザイン作業に修正
- 開発スケジュールのスプレッドシート ⇢ 削除、併せて全体会などのチーム特有の語句があったのでそれも削除

2021-04-14 04:52 UTC, sukechannnn commented on teams/ecbooster.md
> +    - 詳細はこちら的な何か
気づいて頂いてありがとうございます！
350c5da で `スクラム開発` をリンクにしました 🙏

2021-04-14 05:14 UTC, meihong commented on teams/ecbooster.md
> +- [EC Booster 開発スプリント回し方](https://docs.google.com/presentation/d/e/2PACX-1vTQY639rUAwDDtLfj_c9WbU1E0IlDSFzAbrP-XFCmbg8V_sNKPX_pCvKpiy50CQpS02nXvZnQHBb6JT/pub?start=false&loop=false&delayms=3000)
確認しました。大丈夫だと思います！

2021-04-14 05:14 UTC, meihong commented on teams/ecbooster.md
> +    - 詳細はこちら的な何か
これでokだと思います！

2021-04-14 05:15 UTC, meihong approved these changes
これでよいと思います。
何かあれば気づきベースで更新できれば！

2021-04-14 05:45 UTC, sukechannnn commented
ありがとうございます！マージします 🙆

2021-04-14 05:45 UTC, merged